name: Deploy project plan to heroku

# CurioCitY change to master branch
on: push

jobs:
  build-frontend:
    name: build project plan react frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: run npm install and build
        run: |
          cd curiocityfrontend
          npm install
          npm run build
      - name: upload frontend build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: curiocityfrontend/build/

  build-backend:
    name: build jar file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download frontend build artifacts
        uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: curiocitybackend/src/main/resources/static
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Maven
        run: mvn -B package --file ./curiocitybackend/pom.xml
      - name: upload curiocity.jar
        uses: actions/upload-artifact@v2
        with:
          name: curiocity.jar
          path: curiocitybackend/target/curiocity.jar





